//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LaserSystem.rc
//
#define IDS_STRING1                     1
#define IDD_ABOUTBOX                    100
#define IDD_FORMVIEW                    101
#define IDD_DIALOG_COGNEXSHOWVIEW       102
#define IDR_MAINFRAME                   128
#define IDR_TABWNDTYPE                  129
#define IDS_STATIC1                     129
#define IDD_FORM                        130
#define IDD_PROPERTIES                  134
#define IDB_SMALL_IMAGELIST             136
#define IDB_IMAGELIST                   137
#define IDD_SINGLEINPUT                 141
#define IDD_MOTIONTESTVIEW              142
#define IDB_LEDGREENON                  145
#define IDB_LEDGREENOFF                 146
#define IDI_HOME                        149
#define IDD_SINGLEOUTPUTVIEW            151
#define IDD_SIGNALINPUTVIEW             152
#define IDD_MOTIONCONTESTVIEW           153
#define IDI_ARROWLEFT                   154
#define IDI_ARROWRIGHT                  155
#define IDI_MOVERIGHT                   156
#define IDI_MOVELEFT                    157
#define IDD_FILEINFOSETTINGVIEW         158
#define IDD_OPERREFCOORDVIEW            162
#define IDI_SAVEP                       165
#define IDD_FUNCTIONTESTVIEW            166
#define IDI_LASERWARMUP                 167
#define IDI_WARMUP                      167
#define IDI_LASER                       168
#define IDI_MATRIX                      169
#define IDI_LAMPON                      170
#define IDI_LAMPOFF                     171
#define IDI_LEDON                       172
#define IDI_LEDOFF                      173
#define IDI_ARROWDOWN                   174
#define IDI_ARROWUP                     175
#define IDI_STOP                        176
#define IDD_MAINFORMVIEW                177
#define IDD_MOTIONPARAMETER             178
#define IDI_CHECKED                     179
#define IDI_UNCHECKED                   180
#define IDD_TESTFUNCTIONVIEW            182
#define IDI_NSHAPE                      183
#define IDI_CM                          183
#define IDI_SSHAPE                      184
#define IDI_LW                          184
#define IDI_OPENFILE                    185
#define IDI_SELECTBLOCK                 187
#define IDI_ICON1                       188
#define IDI_ICON2                       189
#define IDD_SYSPARAMVIEW                191
#define IDI_RESET                       194
#define IDI_START                       195
#define IDD_TOOLSPARAVIEW               200
#define IDD_TOOLPARAVIEW                200
#define IDI_RESETCARD                   203
#define IDI_EXIT                        205
#define IDI_PAUSE                       206
#define IDI_ADJUST                      207
#define IDI_PARAMETER                   208
#define IDI_END                         211
#define IDI_LASERPOWERON                213
#define IDD_IMAGEPARASETVIEW            214
#define IDI_ICON3                       215
#define IDC_SELCUR                      216
#define IDI_SET                         218
#define IDI_DEL                         219
#define IDI_MODIFY                      220
#define IDI_ADD                         221
#define IDI_MPATTERN                    227
#define IDI_FIDUPOS                     228
#define IDI_MPATTERNCRT                 229
#define IDI_CHANGER                     230
#define IDI_CHANGEL                     231
#define IDB_BITMAP1                     232
#define IDI_SHOWWHOLE                   233
#define IDI_SHOWPART                    234
#define IDD_POSITIONERRVALUEVIEW        235
#define IDD_DLG_WARNINGINFO             237
#define IDR_SUBFUN                      239
#define IDI_LASERPOWEROFF               240
#define IDI_ZDOWN                       243
#define IDI_ZUP                         246
#define IDD_DLG_LOGIN                   251
#define IDD_LOGINVIEW                   253
#define IDI_DTUNLOAD                    256
#define IDI_UTUNLOAD                    257
#define IDI_UNLOAD                      259
#define IDI_PUNLOAD                     261
#define IDI_TOLOAD                      262
#define IDI_PLOAD                       265
#define IDI_LOAD                        267
#define IDC_NODRAGGING                  268
#define IDD_PROCPARAVIEW                268
#define IDD_DLG_MANUFINDFID             274
#define IDD_POINTCONTRLVIEW             279
#define IDR_MENUSHOWPFUN                280
#define IDD_SYSTEMLOG                   281
#define IDI_CLEAN                       283
#define IDI_PASS                        285
#define IDI_FILEPOINT                   286
#define IDI_ZERO                        287
#define IDI_TEST                        288
#define IDI_DISPLAY                     289
#define IDD_LAMPSADJUST                 290
#define IDI_CLOSE                       293
#define IDD_DELLOG                      294
#define IDI_LAMP                        298
#define IDI_FIDU                        300
#define IDI_OPTIM                       301
#define IDI_ZOOMIN                      302
#define IDI_ZOOMINM                     303
#define IDI_ICON4                       304
#define IDI_ICON5                       305
#define IDI_ZOOMOUT                     306
#define IDI_ZOOMNONE                    307
#define IDB_BITMAP2                     316
#define IDD_DLG_LOADANDUNLOAD           320
#define IDI_ICON6                       321
#define IDI_MOVE                        326
#define IDI_SNAP                        327
#define IDI_DOWN                        328
#define IDI_UP                          329
#define IDI_SORB                        330
#define IDB_FOLDERS                     332
#define IDD_DIALOG1                     336
#define IDC_CURSOR1                     339
#define IDC_CURSOR2                     342
#define IDD_DIALOG2                     343
#define IDC_CURSOR3                     344
#define IDD_WARNINGINFO                 353
#define IDC_CURSOR4                     355
#define IDD_DIALOG3                     356
#define IDD_DLG_ROTATE                  356
#define IDD_DIALOG4                     357
#define IDD_DLG_DRILLONEHOLE            357
#define IDC_CURSOR5                     359
#define IDD_DIALOG_PRECISION            360
#define IDC_CURSOR6                     361
#define IDI_LEDGREEN                    363
#define IDD_DIALOG5                     365
#define IDD_DIALOG6                     366
#define IDD_DIALOG7                     367
#define IDC_CURSOR7                     368
#define IDD_DIALOG8                     369
#define IDD_DLG_SCALESET                371
#define IDD_DLG_PROCLOGGIN_SN           373
#define IDC_CURSOR8                     374
#define IDD_DLG_PROCLOGIN_FZ            375
#define IDD_DLG_PROCLOGIN_SN            376
#define IDC_CURSOR9                     381
#define IDD_DIALOG9                     382
#define IDD_DIALOG10                    383
#define IDC_CURSOR10                    388
#define IDD_DIALOG11                    389
#define IDC_CURSOR11                    390
#define IDC_CURSOR12                    391
#define IDC_CURSOR13                    392
#define IDD_DIALOG12                    397
#define IDD_MARKMAKE                    401
#define IDD_DLG_IMESSETTING             402
#define IDD_INGREDIENTINFOVIEW          403
#define IDD_DLG_MODESWITCHLOGIN         404
#define IDC_EDIT                        1000
#define IDC_EDT_LASERPOWERX             1000
#define IDC_EDIT_SERVER                 1000
#define IDC_COMBO1                      1001
#define IDC_COMBO                       1001
#define IDC_EDIT3                       1001
#define IDC_EDT_LASERPOWERY             1001
#define IDC_CMB_INTEGERNUM              1001
#define IDC_EDT_LASERRELEASE            1001
#define IDC_CMB_LASERHEAD               1001
#define IDC_EDT_BITPERMM                1001
#define IDC_EDT_PASSWORD                1001
#define IDC_EDT_PLS2RELEASE             1001
#define IDC_COGPMALIGNEDIT1             1001
#define IDC_EDIT_PORT                   1001
#define IDC_LIST1                       1002
#define IDC_LIST                        1002
#define IDC_EDIT4                       1002
#define IDC_EDT_LASERPOWERZ             1002
#define IDC_EDT_LASERPERIOD             1002
#define IDC_CMB_MATRIXHEAD              1002
#define IDC_EDT_CCDFOCUSRT              1002
#define IDC_EDT_PASSWORDC               1002
#define IDC_EDT_FIDX2                   1002
#define IDC_EDT_PLS3RELEASE             1002
#define IDC_BUTTON_RESULT               1002
#define IDC_EDIT5                       1003
#define IDC_EDT_CCDOFFX                 1003
#define IDC_EDT_LASERFOCUSLT            1003
#define IDC_EDT_FIDY2                   1003
#define IDC_CMB_DRILLBARCODEHEAD        1003
#define IDC_EDT_PLS4RELEASE             1003
#define IDC_BUTTON_MAKETEMPLATE         1003
#define IDC_COMBO_USERRIGHT             1003
#define IDC_VISIBLETAB                  1004
#define IDC_EDIT6                       1004
#define IDC_EDT_CCDOFFY                 1004
#define IDC_EDT_LASERFOCUSRT            1004
#define IDC_EDT_FIDX3                   1004
#define IDC_CMB_DRILLBARCODETYPE        1004
#define IDC_EDT_PLS5RELEASE             1004
#define IDC_BUTTON_LOADVPP              1004
#define IDC_EDT_MATERIALCODE            1004
#define IDC_ENABLE                      1005
#define IDC_EDIT7                       1005
#define IDC_EDT_CCDOFFZ                 1005
#define IDC_EDT_CCDDISTANCEY            1005
#define IDC_EDT_FIDY3                   1005
#define IDC_EDT_GLVADJPOSY              1005
#define IDC_BUTTON_SAVEVPP              1005
#define IDC_SET                         1006
#define IDC_ENABLETAB                   1007
#define IDC_BUTTON1                     1007
#define IDC_PARASAVE                    1007
#define IDC_BT_MOVETO_P2                1007
#define IDC_BT_SAVE_LASERPOWER_P        1007
#define IDC_BT_SETTESTP                 1007
#define IDC_BT_SAVE_LASERPOWER_P2       1008
#define IDC_BT_SAVE_FTHETA_PARA         1008
#define IDC_BT_RESETTESTP               1008
#define IDC_BARCPRINT                   1008
#define IDC_BUTTON9                     1008
#define IDC_IN_1                        1009
#define IDC_BTN_TESTTHICKNESS           1009
#define IDC_BTN_MODIFY                  1009
#define IDC_IN_0                        1010
#define IDC_BUTTON_SELECTBMP            1010
#define IDC_BTN_SET                     1010
#define IDC_BT_AXISY_HOME               1011
#define IDC_BUTTON_IN_LOAD              1011
#define IDC_BTN_SAVE                    1011
#define IDC_BT_AXISX_HOME               1012
#define IDC_BUTTON_IN_SAVE              1012
#define IDC_BT_AXISW_HOME               1013
#define IDC_BUTTON_CALIBRATE_LOAD       1013
#define IDC_BT_MOVETO_P1                1014
#define IDC_BUTTON_CALIOBRATE_SAVE      1014
#define IDC_BT_AXISZ_HOME               1015
#define IDC_BUTTON3                     1016
#define IDC_BT_HOMEALL                  1016
#define IDC_EDIT2                       1017
#define IDC_EDT_POS1                    1017
#define IDC_EDT_LOADPITCHPOS            1017
#define IDC_EDT_TOOLDIAMETER            1017
#define IDC_EDT_OFFAXISY                1017
#define IDC_EDIT_RR                     1018
#define IDC_EDT_TOOLINDEX               1018
#define IDC_EDIT_AMPLOYEEID             1018
#define IDC_EDIT_LC                     1019
#define IDC_EDIT_LR                     1020
#define IDC_BUTTON2                     1021
#define IDC_BT_LASERWARMUP              1021
#define IDC_BT_TOLOADPOS                1021
#define IDC_BT_ZUP                      1021
#define IDC_BTN_DEL                     1021
#define IDC_BT_LOGSAVE                  1021
#define IDC_BT_ZOOMFRAME                1021
#define IDC_BT_LOADSTH_UP               1021
#define IDC_EDIT_LINFRARED              1021
#define IDC_BUTTON4                     1022
#define IDC_BT_EXIT                     1022
#define IDC_BT_TOOLINSERT               1022
#define IDC_BT_STOPEXCCARD2             1022
#define IDC_BT_LEARNPATTERN             1022
#define IDC_BTN_LOGIN                   1022
#define IDC_EDIT_RINFRARED              1022
#define IDC_BUTTON5                     1023
#define IDC_BT_MANU_UP                  1023
#define IDC_BT_SETTABPOS                1023
#define IDC_BT_TOOLDEL                  1023
#define IDC_BT_SETPARAMETER             1023
#define IDC_BT_CHANGECHAN               1023
#define IDC_BUTTON6                     1024
#define IDC_BT_MANU_DOWN                1024
#define IDC_BT_STEP_RIGHT               1024
#define IDC_BT_PASS                     1024
#define IDC_BUTTON7                     1025
#define IDC_BT_LASER_WARMUP             1025
#define IDC_BT_MANU_RIGHT               1025
#define IDC_BT_STEP_LEFT                1025
#define IDC_BT_LASER_POWERTEST          1026
#define IDC_BT_UN_LOADSTH_UP            1026
#define IDC_CHK_OUT_0                   1027
#define IDC_BT_UNLOADPOS                1027
#define IDC_CHK_OUT_1                   1028
#define IDC_BT_LOADPOS                  1028
#define IDC_BT_DRILLMATRIX              1029
#define IDC_CHK_OUT_16                  1029
#define IDC_BT_MANU_LEFT                1030
#define IDC_CHK_OUT_17                  1030
#define IDC_BT_MANU_STOP                1031
#define IDC_CHK_OUT_32                  1031
#define IDC_CHK_OUT_2                   1032
#define IDC_BT_MANU_STOP2               1032
#define IDC_CHK_OUT_3                   1033
#define IDC_BT_RUN_START                1034
#define IDC_CHK_OUT_4                   1034
#define IDC_BT_RUN_PAUSE                1035
#define IDC_CHK_OUT_5                   1035
#define IDC_CHK_OUT_6                   1036
#define IDC_CHK_DRILLMACHINFO           1036
#define IDC_BT_RUN_CONT                 1037
#define IDC_CHK_OUT_7                   1037
#define IDC_CHK_DRILLDAYINFO            1037
#define IDC_CHK_OUT_8                   1038
#define IDC_CHK_DRILLTIMEINFO           1038
#define IDC_BT_RUN_END                  1039
#define IDC_CHK_OUT_9                   1039
#define IDC_CHK_DRILLLOTINFO            1039
#define IDC_CHK_OUT_10                  1040
#define IDC_CHK_DRILLSTRINGINFO         1040
#define IDC_BT_TESTLASERPOWER           1041
#define IDC_CHK_OUT_11                  1041
#define IDC_BT_WARMUPLASER              1042
#define IDC_CHK_OUT_12                  1042
#define IDC_CHK_OUT_13                  1043
#define IDC_BT_AXISZ_HOME_1             1043
#define IDC_CHK_OUT_14                  1044
#define IDC_BT_AXISW_HOME_1             1044
#define IDC_CHK_OUT_15                  1045
#define IDC_BT_AXISX_HOME_2             1045
#define IDC_CHK_OUT_18                  1046
#define IDC_BT_AXISY_HOME_2             1047
#define IDC_CHK_OUT_19                  1047
#define IDC_BT_AXISX_HOME_1             1048
#define IDC_CHK_OUT_20                  1048
#define IDC_BT_AXISY_HOME_1             1049
#define IDC_CHK_OUT_33                  1049
#define IDC_CHK_OUT_34                  1050
#define IDC_RADIO1                      1051
#define IDC_CHK_OUT_35                  1051
#define IDC_RAD_PROCESSDIRN             1051
#define IDC_RADIO2                      1052
#define IDC_CHK_OUT_36                  1052
#define IDC_RAD_MANUPROC                1052
#define IDC_CHK_OUT_21                  1053
#define IDC_RADIO3                      1053
#define IDC_RAD_AUTOPROC                1053
#define IDC_CHK_OUT_22                  1054
#define IDC_BT_SELECTFILE               1054
#define IDC_CHK_OUT_23                  1055
#define IDC_COMBO2                      1055
#define IDC_CMB_SELECTAXIS              1055
#define IDC_CHK_OUT_24                  1056
#define IDC_STATIC_DISPLAYBLOCK         1056
#define IDC_COMBO_INN_POLARITY          1056
#define IDC_CHK_OUT_25                  1057
#define IDC_CHECK1                      1057
#define IDC_DISPLAYPIONT                1057
#define IDC_CHK_LEFTHEAD                1057
#define IDC_CHK_USETOOL                 1057
#define IDC_SELECTCHECK                 1057
#define IDC_SELECTMANUALHECK            1057
#define IDC_CHK_SELCTHEIGHT             1057
#define IDC_CHK_OUT_26                  1058
#define IDC_DISPLAY                     1058
#define IDC_CHK_ENFIDUCIAL2             1058
#define IDC_CHK_OUT_27                  1059
#define IDC_CHK_ENFIDUCIAL3             1059
#define IDC_CHK_OUT_28                  1060
#define IDC_EDT_MOTIONCARDSN1           1060
#define IDC_CHK_ENFIDUCIAL4             1060
#define IDC_CHK_OUT_29                  1061
#define IDC_EDT_MOTIONCARDSN2           1061
#define IDC_CHK_OUT_PLANER              1061
#define IDC_CHK_OUT_30                  1062
#define IDC_EDT_MOTIONCARDSN3           1062
#define IDC_CHK_OUT_31                  1063
#define IDC_BT_MCSNSET                  1063
#define IDC_CHK_OUT_37                  1064
#define IDC_EDT_MACHINESN               1064
#define IDC_BT_MCSNSET2                 1064
#define IDC_BT_GLVCCDPSET               1064
#define IDC_CHK_OUT_38                  1065
#define IDC_EDT_LOTID                   1065
#define IDC_BT_LASERSET                 1065
#define IDC_EDT_LOTIDFIX                1065
#define IDC_CHK_OUT_39                  1066
#define IDC_EDT_SCANSIZE                1066
#define IDC_CHK_OUT_40                  1067
#define IDC_RAD_PROCESSDIR              1067
#define IDC_CHK_OUT_41                  1068
#define IDC_RADIO4                      1068
#define IDC_CHK_OUT_42                  1069
#define IDC_BT_MCSNRESET                1069
#define IDC_CHK_OUT_43                  1070
#define IDC_EDT_SELECTFILE              1070
#define IDC_BT_MCSNRESET2               1070
#define IDC_BT_GLVCCDPRESET             1070
#define IDC_CHK_OUT_44                  1071
#define IDC_RADIO5                      1071
#define IDC_BT_LASERRESET               1071
#define IDC_CHK_OUT_45                  1072
#define IDC_RADIO6                      1072
#define IDC_CHK_OUT_46                  1073
#define IDC_EDT_PLSRELEASE              1073
#define IDC_CHK_OUT_47                  1074
#define IDC_EDT_PLSPERIOD               1074
#define IDC_CHK_OUT_48                  1075
#define IDC_EDT_JUMPDELAY               1075
#define IDC_CHK_OUT_49                  1076
#define IDC_EDT_JUMPSPEED               1076
#define IDC_CHK_OUT_50                  1077
#define IDC_EDT_LASERONTIME             1077
#define IDC_EDT_ADJPLSRELEASE           1077
#define IDC_CHK_OUT_51                  1078
#define IDC_EDT_LASERPOWER              1078
#define IDC_EDT_ADJPLSPERIOD            1078
#define IDC_CHK_OUT_52                  1079
#define IDC_BT_RESET                    1079
#define IDC_EDT_ADJJUMPDELAY            1079
#define IDC_CHK_OUT_53                  1080
#define IDC_BT_SET                      1080
#define IDC_EDT_ADJJUMPSPEED            1080
#define IDC_CHK_OUT_54                  1081
#define IDC_EDT_POS2                    1081
#define IDC_CHK_OUT_55                  1082
#define IDC_EDT_STEPLENGTH              1082
#define IDC_CHK_OUT_56                  1083
#define IDC_CMB_APT                     1083
#define IDC_CMB_TOOLSUBAPT              1083
#define IDC_CHK_OUT_57                  1084
#define IDC_EDT_UNLOADPITCHPOS          1084
#define IDC_CHK_OUT_58                  1085
#define IDC_CMB_SCANHEAD                1085
#define IDC_CHK_OUT_59                  1086
#define IDC_RAD_UNITMETRIC              1086
#define IDC_CHK_OUT_60                  1087
#define IDC_RADIO7                      1087
#define IDC_CHK_OUT_61                  1088
#define IDC_RADIO8                      1088
#define IDC_CHK_OUT_62                  1089
#define IDC_RAD_UNITINCH                1089
#define IDC_CHK_OUT_63                  1090
#define IDC_RAD_ABSOLUTE                1090
#define IDC_RAD_INCREMENTAL             1091
#define IDC_RAD_DATAFORMAT              1092
#define IDC_CMB_DECIMALNUM              1093
#define IDC_EDT_LOADBENCHMARK           1094
#define IDC_EDT_UNLOADBENCHMARK         1095
#define IDC_EDT_LOADLIFTBM              1096
#define IDC_EDT_UNLOADLIFTBM            1097
#define IDC_EDT_TABBENCHMARKX           1098
#define IDC_EDT_TABBENCHMARKY           1099
#define IDC_EDT_TABLOADX                1100
#define IDC_EDT_TABLOADY                1101
#define IDC_EDT_TABUNLOADX              1102
#define IDC_EDT_TABUNLOADY              1103
#define IDC_BT_RESETLOADPOS             1104
#define IDC_BT_RESETTABPOS              1105
#define IDC_BT_SETLOADPOS               1106
#define IDC_TREE1                       1107
#define IDC_CMB_TOOLAPT                 1108
#define IDC_CMB_TOOLMODE                1109
#define IDC_CMB_TOOLINDEX               1110
#define IDC_BT_TOOLADD                  1111
#define IDC_BT_TOOLMODIFY               1112
#define IDC_BT_TOOLSAVE                 1113
#define IDC_BT_STOPEXCCARD1             1117
#define IDC_BT_STOPEXCCARD3             1118
#define IDC_BT_RESETCARD3               1119
#define IDC_BT_RESETCARD1               1120
#define IDC_BT_RESETCARD2               1121
#define IDC_LASERWARMN                  1123
#define IDC_LASERWARMP                  1124
#define IDC_LASERSHUTTERLN              1125
#define IDC_LASERSHUTTERLP              1126
#define IDC_LASERSHUTTERRN              1127
#define IDC_LASERSHUTTERRP              1128
#define IDC_THICKNESSN                  1129
#define IDC_TABLECLAMPP                 1129
#define IDC_THICKNESSP                  1130
#define IDC_TABLECLAMPN                 1130
#define IDC_BT_SLPRESET                 1131
#define IDC_LOADRTHANDVN                1132
#define IDC_BT_SLPSET                   1132
#define IDC_LENSWINDOW2ERROR            1132
#define IDC_LOADRTHANDVP                1133
#define IDC_EDT_THICKNESS               1133
#define IDC_RINGLIGHT2ERROR             1133
#define IDC_LOADPITCHPOS                1134
#define IDC_FILENAME                    1134
#define IDC_TOPHAT1                     1134
#define IDC_LOADLTHANDVP                1135
#define IDC_ST_PROCEDNUM                1135
#define IDC_LENSWINDOW1ERROR            1135
#define IDC_LOADEMPTY                   1136
#define IDC_TOPHAT2                     1136
#define IDC_LOADRTVACCUM                1137
#define IDC_STATIC2                     1137
#define IDC_RINGLIGHT1ERROR             1137
#define IDC_LOADLTVACCUM                1138
#define IDC_BT_SCANADJUST               1138
#define IDC_STATIC67                    1138
#define IDC_LOADLTHANDVN                1139
#define IDC_RADGLVCCDOFFSET             1139
#define IDC_UNLOADRTHANDVN              1140
#define IDC_EDT_OFFAXISX                1140
#define IDC_GAUSSIAN1                   1140
#define IDC_UNLOADRTHANDVP              1141
#define IDC_RADGLVCCDOFFSETR            1141
#define IDC_GAUSSIAN2                   1141
#define IDC_WATERTEMPERTURE             1142
#define IDC_EDT_LASERCLEANX             1142
#define IDC_UNLOADLTHANDVP              1143
#define IDC_EDT_LASERCLEANY             1143
#define IDC_DUSTPRESSURE1               1143
#define IDC_UNLOADRTVACCUM              1144
#define IDC_EDT_CCDFOCUSLT              1144
#define IDC_DUSTPRESSURE2               1144
#define IDC_UNLOADLTVACCUM              1145
#define IDC_BT_GLVCCDSYSOFFSET          1145
#define IDC_DOORPROTECT                 1145
#define IDC_UNLOADLTHANDVN              1146
#define IDC_EDT_OFFAXISZA               1146
#define IDC_UNLOADPUTPOS                1147
#define IDC_BT_FIDUCIALPOS              1147
#define IDC_BT_TESTCCDFOCUS             1147
#define IDC_LOADEMPTY2                  1148
#define IDC_STAT                        1148
#define IDC_BT_TESTLASERFOCUS           1148
#define IDC_WATERPRESS                  1149
#define IDC_BT_STEP_DOWN                1149
#define IDC_UNDERVOLT                   1150
#define IDC_BT_STEP_UP                  1150
#define IDC_OVERVOLT                    1151
#define IDC_BT_STEP_STOP                1151
#define IDC_LOADERPITCHN                1152
#define IDC_EDT_STEPLEN                 1152
#define IDC_LOADERPITCH                 1152
#define IDC_LOADERPITCHP                1153
#define IDC_BT_ADJUSTPATTERN            1153
#define IDC_UNLOADERPITCH               1153
#define IDC_TABRTVACUMM                 1154
#define IDC_BT_UNLOADPCB                1154
#define IDC_TABLTVACUMM                 1155
#define IDC_BT_UNLOADPICTH              1155
#define IDC_AIRPRESSURE                 1156
#define IDC_BUTTON10                    1156
#define IDC_BT_TOUNLOADPOS              1156
#define IDC_BT_UNLOADLVAC               1156
#define IDC_BT_RIGHTHAND_UD             1156
#define IDC_LOADERPUSHUPTO              1157
#define IDC_BT_UN_RIGHTHAND_UD          1157
#define IDC_CCDLIGHTERROR2              1158
#define IDC_BT_LOADPCB                  1158
#define IDC_CCDLIGHTERROR1              1159
#define IDC_BUTTON8                     1159
#define IDC_BT_LEAVE                    1159
#define IDC_BT_UNLOADPOS1               1159
#define IDC_BT_RIGHTSORB                1159
#define IDC_BUTTON_ACCURACYTEST         1159
#define IDC_BT_SETTING                  1159
#define IDC_BTN_IMESSETTING             1159
#define IDC_LOADERPITCHN2               1160
#define IDC_RAD_SELECT                  1160
#define IDC_BT_UN_RIGHTSORB             1160
#define IDC_1842_1ERROR                 1160
#define IDC_LOADERPITCHP2               1161
#define IDC_EDT_CCDDISTANCEX            1161
#define IDC_1842_2ERROR                 1161
#define IDC_FTGATESTATUS                1162
#define IDC_BT_TESTCCDDISTANCE          1162
#define IDC_UNLOADERFULL                1163
#define IDC_GRIDMOTIONPARAM             1163
#define IDC_FTGATESTATUS2               1164
#define IDC_SLIDER1                     1165
#define IDC_SERVOALARMX                 1165
#define IDC_EDIT1                       1166
#define IDC_SDER_RR                     1166
#define IDC_SERVOALARMY                 1166
#define IDC_SDER_RC                     1167
#define IDC_EDT_TXTPLSPERIOD            1167
#define IDC_SERVOALARMZLEFT             1167
#define IDC_EDT_THICKNESSY              1167
#define IDC_EDT_TEXT                    1167
#define IDC_MationStar                  1167
#define IDC_EDIT_UNLOADTIME             1167
#define IDC_EDIT_BEAMDIA                1167
#define IDC_EDT_UPLIMIT                 1167
#define IDC_EDIT_URL                    1167
#define IDC_BT_SAVE                     1168
#define IDC_SDER_LR                     1168
#define IDC_EDT_TXTJUMPSPEED            1168
#define IDC_SERVOALARMZRIGHT            1168
#define IDC_EDT_CHAR                    1168
#define IDC_EDIT10                      1168
#define IDC_EDT_SN_AMPLOYEEID           1168
#define IDC_EDIT_TIMEOUT                1168
#define IDC_BT_SHOWFILEINFO             1169
#define IDC_EDT_TXTJUMPDELAY            1169
#define IDC_SERVOALARMBETPRI            1169
#define IDC_MationDelay                 1169
#define IDC_SDER_LINFRARED              1169
#define IDC_EDIT11                      1169
#define IDC_EDT_SN_PROGRAM              1169
#define IDC_EDIT_ADDMATRIAL             1169
#define IDC_STATIC_DISPLAYPOINT         1170
#define IDC_SERVOALARMBETSUB            1170
#define IDC_MationTime                  1170
#define IDC_SDER_RINFRARED              1170
#define IDC_EDIT_REMMATRIAL             1170
#define IDC_MOTIONSTOPRESET             1171
#define IDC_EDIT_CONTENT                1171
#define IDC_GRIDPOSITIONERR             1172
#define IDC_LASERGASFLUX                1172
#define IDC_ST_PLIMIT                   1173
#define IDC_SWATERCOOLFAULT             1173
#define IDC_ST_HOME                     1174
#define IDC_AOMTEMPROTECT               1174
#define IDC_EDIT_FREQ                   1174
#define IDC_ST_NLIMIT                   1175
#define IDC_TABXERROR                   1175
#define IDC_EDT_UNLOADTRANSPOS          1176
#define IDC_TABYERROR                   1176
#define IDC_EDT_LOADTRANSPOS            1177
#define IDC_THICKNESSERROR1             1177
#define IDC_EDT_TABPITCHY               1178
#define IDC_THICKNESSERROR2             1178
#define IDC_EDT_TABPITCHX               1179
#define IDC_AOMTEMPROTECT2              1179
#define IDC_LASERERROR                  1179
#define IDC_RICHTEXTCTRL1               1180
#define IDC_DRILLMATRIXSWITCH           1180
#define IDC_EDT_BETOFFSET               1181
#define IDC_HOMEALLOK                   1181
#define IDC_EDT_APTOFFSET               1182
#define IDC_READYLOAD                   1182
#define IDC_GRIDBETPOS                  1183
#define IDC_LOADOK                      1183
#define IDC_BT_ZDOWN                    1184
#define IDC_ONLYLEFT                    1184
#define IDC_UNLOADOK                    1185
#define IDC_LOGINGRID                   1186
#define IDC_ALARM                       1186
#define IDC_BTN_ADD                     1187
#define IDC_DEPOTEMPTY                  1187
#define IDC_BTN_MODI                    1188
#define IDC_PUTBOARDONTABABLE           1188
#define IDC_READYTOUNLOADOK             1189
#define IDC_EDT_USERNAME                1190
#define IDC_OVERTIMEALARM               1190
#define IDC_CMB_USERLEVEL               1191
#define IDC_LTHICKNESS                  1191
#define IDC_BTN_OPTIMIZEPATH            1192
#define IDC_RTHICKNESS                  1192
#define IDC_EDT_FIDX4                   1193
#define IDC_EDT_FIDY4                   1194
#define IDC_EDT_FIDX1                   1195
#define IDC_EDT_FIDY1                   1196
#define IDC_BTN_SETFIDOFFSET            1197
#define IDC_FIDCIAL                     1198
#define IDC_BTN_MIRROR                  1199
#define IDC_CMB_PULSENUM                1200
#define IDC_CMB_APERTURE                1201
#define IDC_BT_RESETPROCPARA            1202
#define IDC_BT_SETPROCPARA              1203
#define IDC_BT_SAVEPROCPARA             1204
#define IDC_EDT_PROCTHRESHOLD           1205
#define IDC_EDT_ADJTHRESHOLD            1206
#define IDC_CMB_ADJAPERTURE             1206
#define IDC_ST_PROCINFO                 1207
#define IDC_CHK_RIGHTHEAD               1208
#define IDC_DISPLAYFID                  1209
#define IDC_BT_CONFIRM                  1210
#define IDC_ST_PITCHSTATUS              1211
#define IDC_CHK_OUT_PLANEL              1212
#define IDC_BT_CLEAR                    1213
#define IDC_RADAUTO                     1214
#define IDC_RADMANU                     1215
#define IDC_BT_PITCHPOINT               1216
#define IDC_ST_PCBHOLE                  1217
#define IDC_STATIC3                     1218
#define IDC_LST_TOOL                    1219
#define IDC_CB_COLORSEL                 1220
#define IDC_DATAGRID2                   1222
#define IDC_DATETIMBEFOR                1223
#define IDC_DATETIMEAFTER               1224
#define IDC_BT_FITTER                   1225
#define IDC_COMLOGSEL                   1226
#define IDC_BT_DEL                      1227
#define IDC_BT_TOPOINT                  1228
#define IDC_PCBHOLENUM                  1229
#define IDC_STATICX                     1230
#define IDC_LASERPOWERWAR               1230
#define IDC_STATICY                     1231
#define IDC_ADJUSTWAR                   1231
#define IDC_STATICZ                     1232
#define IDC_STATICZL                    1232
#define IDC_PCBDRILLEDHOLENUM           1232
#define IDC_STATICZ2                    1234
#define IDC_STATICZR                    1234
#define IDC_BT_CLEAN                    1235
#define IDC_BT_CLEANX                   1235
#define IDC_BT_CLEANY                   1236
#define IDC_BT_CLEANZL                  1237
#define IDC_BT_CLEANZR                  1238
#define IDC_BT_LANMP                    1239
#define IDC_BT_SAVELIGHT                1241
#define IDC_SDER_LC                     1242
#define IDC_EDIT_RC                     1245
#define IDC_RADIO_EXT                   1246
#define IDC_TEST                        1248
#define IDC_DATAGRID1                   1250
#define IDC_LIST_DISPLAY                1251
#define IDC_OPENLOGFILE                 1252
#define IDC_ET_PASSWORD                 1255
#define IDC_SAVEANDDEL                  1257
#define IDC_DEL                         1258
#define IDC_SAVE                        1259
#define IDC_BT_CONFORM                  1260
#define IDC_BARCPREVIEW                 1261
#define IDC_STATIC_BARCODEDISPALY       1262
#define IDC_BARCODESTR                  1263
#define IDC_STA_LASERWORKT              1270
#define IDC_RIGHTRCHECK                 1271
#define IDC_RIGHTROPENCHECK             1271
#define IDC_lOADCCDLUMINPARA            1272
#define IDC_RESETCCDLUMINPARA           1272
#define IDC_LCENCHECK                   1273
#define IDC_LEFTCOPENCHECK              1273
#define IDC_RCENCHECK                   1274
#define IDC_RIGHTCOPENCHECK             1274
#define IDC_LEFTROPENCHECK              1275
#define IDC_RAD_EXT                     1276
#define IDC_CCDLUMINSET                 1277
#define IDC_BT_FIRSTFIDUPOS             1278
#define IDC_CHECKLINFRARED              1278
#define IDC_CMB_TXTPULSENUM             1279
#define IDC_CHECKRINFRARED              1279
#define IDC_CMB_TXTPERTURE              1280
#define IDC_EDT_TXTPLSRELEASE           1281
#define IDC_STASTATE                    1282
#define IDC_BT_ZOOMIN                   1283
#define IDC_BT_ZOOMOUT                  1284
#define IDC_BT_ZOOMRESET                1285
#define IDC_EDT_ADJTESTTIME             1286
#define IDC_EDT_LASERPOWERTIME          1287
#define IDC_PRO_LASERPOWAR              1287
#define IDC_PRO_GALVOADJWAR             1288
#define IDC_CHK_STRINGZOOM              1289
#define IDC_EDT_STRZOOM                 1290
#define IDC_BT_ENTER                    1291
#define IDC_TREELOG                     1292
#define IDC_STATIC_PROCCHEK             1294
#define IDC_BTN_TOOLCOLOR               1295
#define IDC_LIST_IO                     1296
#define IDC_LIST_IOINPUT                1297
#define IDC_LIST_IOOUTPUT               1298
#define IDC_DTHIBEFOR                   1298
#define IDC_DTHIAFTER                   1299
#define IDC_COMHISLOGSEL                1300
#define IDC_BT_OPENHISDISPLAY           1301
#define IDC_BT_STUFFRISE                1303
#define IDC_BT_SWITCH                   1304
#define IDC_TUNEPOSXN                   1309
#define IDC_TUNEPOSYN                   1310
#define IDC_UNLOADERPUSHUPTO            1311
#define IDC_TUNEPOSYP                   1312
#define IDC_TUNEPOSXP                   1313
#define IDC_LOADVIBRATEN                1314
#define IDC_LOADVIBRATEP                1315
#define IDC_BT_WAITTOLOAD               1316
#define IDC_BT_LOADTOTABLE              1318
#define IDC_BT_SNAPEX                   1319
#define IDC_DRAGGING                    1320
#define IDC_BT_SNAPIM                   1320
#define IDC_BT_UNLOADRVAC               1327
#define IDC_BT_UNLOADRUPDOWN            1328
#define IDC_BT_LOADPOS2                 1329
#define IDC_BT_LOADPOS1                 1330
#define IDC_BT_LOADRVAC                 1331
#define IDC_BT_LOADRUPDOWN              1332
#define IDC_BT_LOADLVAC                 1333
#define IDC_BT_LOADLUPDOWN              1334
#define IDC_BT_LOADDEPOTUP              1335
#define IDC_BT_LOADDEPOTDOWN            1336
#define IDC_BT_LOADTUNE                 1337
#define IDC_BT_UNLOADDEPOTUP            1338
#define IDC_BT_UNLOADDEPOTDOWN          1339
#define IDC_BT_UNLOADPOS2               1341
#define IDC_BT_UNLOADLUPDOWN            1342
#define IDC_BT_LOADTUNEIM               1343
#define IDC_BT_UNLOADPOS3               1344
#define IDC_BT_UNLOADPOS4               1345
#define IDC_BT_LOADPOS3                 1346
#define IDC_BT_LOADPOS4                 1347
#define IDC_EDT_UNLOADTUNEPOS           1348
#define IDC_EDT_LOADTUNEPOS             1349
#define IDC_BT_UNLOADTABLEPPOS          1350
#define IDC_BT_LOADTABLEPPOS            1351
#define IDC_RADIO9                      1356
#define IDC_RADIO10                     1357
#define IDC_RADIO11                     1358
#define IDC_EDT_LONGPATH_LASERFOCUSRT   1360
#define IDC_EDT_LONHPATH_LASERFOCUSLT   1361
#define C_BT_LONGPATH_TESTLASERFOCUS    1362
#define IDC_EDT_CCDOFFLONGZ             1363
#define IDC_CMB_LONGPATH_ADJAPERTURE    1365
#define IDC_LOADLTVACCUMBACK            1366
#define IDC_LOADRTVACCUMBACK            1367
#define IDC_TUNEPOSXNBACK               1368
#define IDC_TUNEPOSXPBACK               1369
#define IDC_UNLOADLTVACCUMBACK          1370
#define IDC_UNLOADRTVACCUMBACK          1371
#define IDC_CHK_OUT_66                  1373
#define IDC_EDT_PCBTHICKNESS            1374
#define IDC_BT_LEFTSORB                 1375
#define IDC_BT_LEFTHAND_UD              1376
#define IDC_BT_LOADSTH_DOWN             1377
#define IDC_BT_GETBOADPOS               1378
#define IDC_BT_GETTRANSPOS              1379
#define IDC_BT_GETTUNESPOS              1380
#define IDC_BT_PUTBOADPOS               1381
#define IDC_BT_UN_LOADSTH_DOWN          1382
#define IDC_BT_UN_LEFTSORB              1383
#define IDC_BT_UN_LEFTHAND_UD           1384
#define IDC_BT_UN_GETBOADPOS            1385
#define IDC_BT_UN_GETTRANSPOS           1386
#define IDC_BT_UN_GETTUNESPOS           1387
#define IDC_BT_UN_PUTBOADPOS            1388
#define IDC_BT_LOADTEST                 1389
#define IDC_BT_UNLOADTEST               1390
#define IDC_BT_UN_RIGHTHAND_D           1391
#define IDC_BT_LEFTHAND_D               1392
#define IDC_BT_RIGHTHAND_D              1393
#define IDC_BT_UN_LEFTHAND_D            1394
#define IDC_PROC_PARALIST               1395
#define IDC_TEST_THICKNESSR             1396
#define IDC_TEST_THICKNESSL             1397
#define IDC_THICKNESSNR                 1398
#define IDC_THICKNESSPR                 1399
#define IDC_THICKNESSNL                 1400
#define IDC_THICKNESSPL                 1401
#define IDC_UNLOADRTHANDVPSEC           1402
#define IDC_UNLOADLTHANDVPSEC           1403
#define IDC_LOADLTHANDVPSEC             1404
#define IDC_LOADRTHANDVPSEC             1405
#define IDC_CCDDISTANCEPOSY             1407
#define IDC_CCDDISTANCEPOSX             1408
#define IDC_EDT_GLVADJPLSRELEASE        1409
#define IDC_EDT_GLVADJPOSX              1410
#define IDC_STATIC_MIRROR               1411
#define IDC_CCDBOARDTHICK               1413
#define IDC_GALVOBOARDTHICK             1414
#define IDC_XDIFF                       1415
#define IDC_YDIFF                       1416
#define IDC_BTN_ZEROTEST                1417
#define IDC_EDT_TESTTHICKNESS           1418
#define IDC_EDT_PULSECOUNT              1419
#define IDC_RADIO_SHORTPATH             1421
#define IDC_RADIO_LONGPATH              1422
#define IDC_RADIO_MANTHICKNESS          1423
#define IDC_RADIO_AUTOTHICKNESS         1424
#define IDC_BTN_THICKNESS               1425
#define IDC_EDT_THICKNESSX              1426
#define IDC_CMB_TESTAPERTURE            1427
#define IDC_EDT_TESTBOARDTHICKNESS      1428
#define IDC_EDT_BETPRIOFFSET            1429
#define IDC_BT_TEXTTEST                 1430
#define IDC_EDT_REGIONDI                1431
#define IDC_EDT_REGIONDIM               1431
#define IDC_EDT_TEXTHEIGTH              1432
#define IDC_RADIO_NORMALPROC            1433
#define IDC_RADIO_INNERMARK             1434
#define IDC_RADIO_LOCALMARK             1435
#define IDC_BTN_TRANSSAVE               1436
#define IDC_RADIO_SALOCALMARK           1437
#define IDC_EDIT8                       1438
#define IDC_EDT_SCALETHRESHOLD          1438
#define IDC_EDT_SCALETHRESHOLD2         1439
#define IDC_EDT_GLVTHRESHOLD            1440
#define IDC_RADIO_FIXING                1441
#define IDC_EDT_INNERSCALETHRESHOLD     1441
#define IDC_RADIO_INCREASING            1442
#define IDC_CHK_ENABLEMANUMOVE          1446
#define IDC_CHECK2                      1448
#define IDC_CHK_ENABLEAUTOPOWER         1448
#define IDC_CHECKRIGHT                  1448
#define IDC_INCREASING                  1448
#define IDC_CHECK_CONTROL               1448
#define IDC_EDT_AUTOTHICKERROR          1450
#define IDC_BT_APTSWITCH                1451
#define IDC_CHK_ENFIDUCIAL1             1452
#define IDC_CHK_TWOCYCLEMODE            1453
#define IDC_STATIC_SUBAPT               1454
#define IDC_BT_CYCLEDRILLMATRIX         1455
#define IDC_BNT_PARAMTEST               1456
#define IDC_EDT_PROCINNERTHRESHOLD      1457
#define IDC_BNT_PARAMTEST2              1457
#define IDC_CHK_ENABLEAUTOADJUST        1458
#define IDC_BNT_PARAMTEST3              1458
#define IDC_EDT_LASERPOWERST            1459
#define IDC_BNT_PARAMTEST4              1459
#define IDC_STATIC_FILEINFO             1460
#define IDC_BNT_DRILLONEHOLE            1460
#define IDC_EDT_LASERPOWERMAX           1460
#define IDC_EDT_NGTHRESHOLD             1461
#define IDC_LIST_WARNINGINFO            1462
#define IDC_SPIN1                       1463
#define IDC_MationEnd                   1464
#define IDC_RADIOChooseX                1465
#define IDC_RADIOChooseY                1466
#define IDC_BUTTONpause                 1468
#define IDC_CHECKPERIOD                 1469
#define IDC_CHECK_MANSCALE              1470
#define IDC_EDIT_MANSCALEX              1471
#define IDC_STATIC_SCALE                1472
#define IDC_STATIC_SCALE2               1473
#define IDC_STATIC_POLARITY             1473
#define IDC_EDIT_MANSCALEY              1474
#define IDC_STATIC_MFPOL                1474
#define IDC_STATIC_INFPOL               1475
#define IDC_COMBO_MAIN_POLARITY         1476
#define IDC_EDT_WARMPLSRELEASE          1477
#define IDC_FLOWERROR                   1479
#define IDC_STATIC4                     1483
#define IDC_STATIC5                     1484
#define IDC_STATIC6                     1485
#define IDC_STATIC22                    1486
#define IDC_STATIC9                     1487
#define IDC_STATIC17                    1488
#define IDC_STATIC27                    1489
#define IDC_STATIC7                     1490
#define IDC_STATIC8                     1491
#define IDC_STATIC10                    1492
#define IDC_STATIC11                    1493
#define IDC_STATIC12                    1494
#define IDC_STATIC13                    1495
#define IDC_STATIC14                    1496
#define IDC_STATIC15                    1497
#define IDC_STATIC16                    1498
#define IDC_STATIC18                    1499
#define IDC_STATIC19                    1500
#define IDC_STATIC20                    1501
#define IDC_STATIC21                    1502
#define IDC_STATIC23                    1503
#define IDC_STATIC24                    1504
#define IDC_STATIC25                    1505
#define IDC_STATIC26                    1506
#define IDC_STATIC28                    1507
#define IDC_STATIC29                    1508
#define IDC_STATIC30                    1509
#define IDC_STATIC31                    1510
#define IDC_STATIC32                    1511
#define IDC_STATIC33                    1512
#define IDC_STATIC34                    1513
#define IDC_STATIC35                    1514
#define IDC_STATIC36                    1515
#define IDC_STATIC37                    1516
#define IDC_STATIC38                    1517
#define IDC_STATIC39                    1518
#define IDC_STATIC40                    1519
#define IDC_STATIC41                    1520
#define IDC_STATIC42                    1521
#define IDC_STATIC43                    1522
#define IDC_STATIC44                    1523
#define IDC_STATIC45                    1524
#define IDC_STATIC46                    1525
#define IDC_STATIC47                    1526
#define IDC_STATIC48                    1527
#define IDC_STATIC49                    1528
#define IDC_STATIC50                    1529
#define IDC_STATIC51                    1530
#define IDC_STATIC52                    1531
#define IDC_STATIC53                    1532
#define IDC_STATIC54                    1533
#define IDC_STATIC55                    1534
#define IDC_STATIC56                    1535
#define IDC_STATIC57                    1536
#define IDC_STATIC58                    1537
#define IDC_STATIC59                    1538
#define IDC_STATIC60                    1539
#define IDC_STATIC61                    1540
#define IDC_STATIC62                    1541
#define IDC_STATIC63                    1542
#define IDC_STATIC64                    1543
#define IDC_STATIC65                    1544
#define IDC_BETFACTOR                   1545
#define IDC_ST_DRILLEDHOLES             1546
#define IDC_ST_CURAREA                  1547
#define IDC_CHECKLEFT                   1548
#define IDC_CURAREA                     1549
#define IDC_ST_CURUSER                  1551
#define IDC_EDT_JUMPLENTH               1553
#define IDC_EDT_Z_JUMPDELAY             1554
#define IDC_EDT_REGIONPOINTDIS          1555
#define IDC_FIDRETRY                    1557
#define IDC_FITBET                      1558
#define IDC_BUTTONLASERFOCUS            1559
#define IDC_BUTTONAPERTURE              1560
#define IDC_CHECK_PATHSHOW              1561
#define IDC_EDIT1_BASEDELAY             1562
#define IDC_BTN_ROTATE                  1563
#define IDC_ROTATE90                    1567
#define IDC_ROTATE180                   1568
#define IDC_ROTATE270                   1569
#define IDC_RADIO_SCALETHRESHOLD        1585
#define IDC_RADIO_SCALETHRESHOLD2       1586
#define IDC_EDIT_PLUSETIMES             1586
#define IDC_CLEAR_NG                    1588
#define IDC_NG_SUM                      1589
#define IDC_STATICNG                    1590
#define IDC_FIXING                      1591
#define IDC_DRILLSCALE                  1592
#define IDC_EDT_LOTIDINC                1593
#define IDC_CHK_DRILLAXISNO             1594
#define IDC_CLR_HOLES                   1595
#define IDC_HOLES_SUM                   1596
#define IDC_CHK_3FID                    1597
#define IDC_CHK_MANUFID                 1598
#define IDC_BUTTON_ACCURACYADJUST       1599
#define IDC_BUTTON_ACCURAY              1600
#define IDC_STATIC_TABLEDELAY           1601
#define IDC_STATIC_TABLEDELAYUS         1602
#define IDC_BUTTON_LOCATIONREPEATABILITY 1603
#define IDC_BUTTON_DATATESTREPEATABILITY 1604
#define IDC_EDIT_TABLEDELAY             1605
#define IDC_STATIC_SCALEBEF             1606
#define IDC_STATIC_SCALEAFT             1607
#define IDC_STATIC_PWMAXBEF             1608
#define IDC_STATIC_PWMAXAFT             1609
#define IDC_MATCH                       1610
#define IDC_MATCHSCORE                  1611
#define IDC_STATIC_INNERSCALE           1612
#define IDC_STATIC_LRSCALE              1613
#define IDC_RADIO_MANSCALE              1614
#define IDC_RADIO_REFSCALE              1615
#define IDC_LOADAVGSCALE                1616
#define IDC_CHECKSCALETHRD              1617
#define IDC_ONEAXIS                     1618
#define IDC_LEFTAXIS                    1619
#define IDC_RIGHTAXIS                   1620
#define IDC_CHECKMANSCALE               1621
#define IDC_EDIT_NOPROCESSID            1622
#define IDC_STATIC_NOPROCESSID          1623
#define IDC_COMBO_OVERPCB               1626
#define IDC_CHECK_OVERBORAD             1627
#define IDC_STATICLINFRARED             1628
#define IDC_CHECK_OVERBSELECT           1629
#define IDC_CHECKSELECTOTHERS           1630
#define IDC_CHECK_DRILLREGION           1631
#define IDC_STATICRSHORT                1635
#define IDC_STATICLSHORT                1636
#define IDC_CHECK_TRIALVERSION          1637
#define IDC_STATIC_TRIALDAYS            1638
#define IDC_EDIT_TRIAL                  1639
#define IDC_BUTTON_TRIALOK              1640
#define IDC_STATIC_RESTDATS             1641
#define IDC_STATIC_LOADTINE             1642
#define IDC_STATIC_LOADUNIT             1643
#define IDC_STATIC_UNLOADTINE           1644
#define IDC_STATIC_LOADUNIT2            1645
#define IDC_BUTTON_SET                  1646
#define IDC_EDIT_LOADTIME               1647
#define IDC_CHECK_NULLDRILLHOLES        1648
#define IDC_STATIC_DISTANCEVALUE        1649
#define IDC_EDIT_DISTANCEVALUE          1650
#define IDC_STATIC_DISTANCEVALUEUM      1651
#define IDC_BUTTON_ACCURACYTABLE        1652
#define IDC_CHK_CIRCLEPROCMODE          1653
#define IDC_EDIT_BEAMSTEP               1654
#define IDC_SCALESETGRID                1655
#define IDC_EDT_DOWNLIMIT               1656
#define IDC_BTN_DELETE                  1657
#define IDC_CHK_MANEDITIN               1658
#define IDC_EDT_SN_LOTID                1659
#define IDC_EDT_FZ_PROGRAM              1660
#define IDC_CHECK_PRECISION1            1661
#define IDC_EDT_FZ_LOTID                1661
#define IDC_CHECK_PRECISION2            1662
#define IDC_EDT_FZ_AMPLOYEEID           1662
#define IDC_CHECK_PRECISION3            1663
#define IDC_EDT_FZ_PROCCOUNT            1663
#define IDC_CHECK_PRECISION4            1664
#define IDC_BTN_FZ_VERIFY               1664
#define IDC_CHECK_PRECISION5            1665
#define IDC_BTN_FZ_STARTUP              1665
#define IDC_CHECK_PRECISION6            1666
#define IDC_STATIC_VERIFYSTATUS         1666
#define IDC_CHECK_PRECISION7            1667
#define IDC_BTN_SN_OPENFILE             1667
#define IDC_CHECK_PRECISION8            1668
#define IDC_SCROLLBAR1                  1668
#define IDC_CHECK_PRECISION9            1669
#define IDC_BTN_FZ_ENDPROC              1669
#define IDC_BNT_SCANSIZE                1669
#define IDC_CHECK_PRECISION10           1670
#define IDC_BUTTON_CORRECTIONTABLE      1670
#define IDC_CHECK_PRECISION11           1671
#define IDC_ANIMATE1                    1671
#define IDC_CHECK_PRECISION12           1672
#define IDC_STATIC_GALVO                1672
#define IDC_CHECK_PRECISION13           1673
#define IDC_STATIC_TABLE                1673
#define IDC_CHECK_PRECISION14           1674
#define IDC_EDT_TEMPERATURE             1674
#define IDC_CHECK_PRECISION15           1675
#define IDC_STATIC_TEMPERATURE          1675
#define IDC_CHECK_PRECISION16           1676
#define IDC_CHECK_DRILLCOIL             1676
#define IDC_EDT_SN_PCBCOUNT             1677
#define IDC_BNT_COLORSAVE               1678
#define IDC_BTN_COLORSAVE               1678
#define IDC_EDIT_STEPSCALE              1679
#define IDC_BT_MARKTEST                 1680
#define IDC_BMPDISPLAY                  1682
#define IDC_RAD_MARKTYPE                1683
#define IDC_CHK_WHITEINBLACK            1684
#define IDC_EDT_MARKSIZE                1685
#define IDC_BTN_AGVL                    1686
#define IDC_BTN_AGVUL                   1687
#define IDC_EDT_FILENAMENEW             1687
#define IDC_BTN_AGVULANDL               1688
#define IDC_EDIT_IDTTIME                1689
#define IDC_EDIT_MOTHPASSWORD           1690
#define IDC_EDT_SN_PRODID               1691
#define IDC_EDT_SN_AMPLOYEEDEPT         1692
#define IDC_DATETIMEUPLOADNIGHT         1693
#define IDC_STATIC_IDCARD               1694
#define IDC_EDIT_USERIDCARD             1695
#define IDC_EDIT_STAFFID                1702
#define IDC_EDT_STAFFID                 1702
#define IDC_CHECK_HEARTBEAT             1705
#define IDC_EDIT_MACHINE                1706
#define IDC_EDIT_PASSWORD               1707
#define IDC_BTN_PATTERNSWITCH           1714
#define IDC_EDT_BARCODE                 1715
#define IDC_GRIDPROCPARA                1716
#define IDC_LABELTABLE                  1717
#define IDC_STA_SSEMP                   1718
#define IDC_BTN_GETINGREDIENTS          1719
#define IDC_EDIT_RESPONSE               1720
#define IDC_DATETIMEUPLOAD              1724
#define IDC_STATIC1                     2136
#define IDC_STATIC66                    2137
#define IDC_HANDCUR                     3010
#define IDM_ENUMPANES                   32771
#define IDM_PROPERTIES                  32772
#define ID_SMALL                        32773
#define ID_FUN_DRILLMATRIX              32773
#define ID_FUN_LOADER                   32774
#define ID_FUN_UNLOADER                 32775
#define ID_FUN_LASERWARNUP              32776
#define ID_FUN_TABLEOUT                 32777
#define ID_MENUZOOMIN                   32778
#define ID_MENUZOOMOUT                  32779
#define ID_MENURESET                    32780
#define ID_MENUMOVE                     32781
#define ID_RUN_PANE                     -32755
#define ID_FILESET_PANE                 32782
#define ID_IMAGE_PANE                   -32753
#define ID_PORW_PANE                    32784
#define ID_SHOWPOINT_PANE               32785
#define ID_SYSTEMPARA_PANE              32786
#define ID_OPRATECOORD_PANE             -32749
#define ID_WORKPARA_PANE                32788
#define ID_SINGALINPUT_PANE             32789
#define ID_SINGALOUTPUT_PANE            32790
#define ID_MOTORTEST_PANE               32791
#define ID_FUNCTIONTEST_PANE            32792
#define ID_TABLESUCTIONON               32793
#define ID_TABLESUCTIONOFF              32794
#define ID_MENUPCBDATA1                 32799
#define ID_MENUPCBDATA2                 32800
#define ID_MENUPCBDATA3                 32801
#define ID_MENUPCBDATA4                 32802
#define ID_MENUPCBDATA5                 32803
#define ID_MENUPCBDATA6                 32804
#define ID_MENUOPRATOR1                 32805
#define ID_MENUOPRATOR2                 32806
#define ID_MENUOPRATOR3                 32807
#define ID_MENUOPRATOR4                 32808
#define ID_MENUPOWER1                   32809
#define ID_MENUPOWER2                   32810
#define ID_MENUPOWER3                   32811
#define ID_MENUPOWER4                   32812
#define ID_MENUPOWER5                   32813
#define ID_MENUPOWER6                   32814
#define ID_MENUPOWER7                   32815
#define ID_MENUFILEPRO1                 32816
#define ID_MENUFILEPRO2                 32817
#define ID_MENUFILEPRO3                 32818
#define ID_MENUFILEPRO4                 32819
#define I32821                          32821
#define ID_POWER_TEST                   32821
#define ID_DRILLCOPPER                  32822
#define ID_PRECISIONTEST                32824
#define ID_LASERFOCUSTEST1              32825
#define ID_LASERFOCUSTEST2              32826
#define ID_APERTURETEST                 32828
#define ID_TABLETEST                    32829
#define ID_MENUONLYANOREVERSE           32831
#define ID_MENUONLYAREVERSE             32832
#define ID_MENUAANDBDOUBLE              32833
#define ID_MENUONLYB                    32834
#define ID_MENUDOUBLEAXIS               32835
#define ID_MENUONLYLEFT                 32836
#define ID_MENUONLYRIGHT                32837
#define ID_MENUASIDEDISPLAY             32838
#define ID_MENUBSIDEDISPLAY             32839
#define ID_GFX_SMALLICON                50000
#define ID_GFX_LARGEICON                50001
#define ID_GFX_RENAMEITEM               50002
#define ID_GFX_REMOVEITEM               50003
#define IDS_OPTICALPATHMODE             61446
#define IDS_BEAMMODE                    61447
#define IDS_APTNO                       61448
#define IDS_PROCSTATUS                  61449
#define IDS_GALVOLEFTTEST               61450
#define IDS_GALVORIGHTTEST              61451
#define IDS_POWERLEFTTEST               61452
#define IDS_POWERRIGHTTEST              61453
#define IDS_PROCAXISMODE                61454
#define IDS_FLOWPATHMODE                61455
#define IDS_CURRENTFLOWSTATUS           61456
#define IDS_CURRENTFILEDISPLAY          61457
#define IDS_CURRENTMACHINESTATUS        61458

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        405
#define _APS_NEXT_COMMAND_VALUE         32840
#define _APS_NEXT_CONTROL_VALUE         1696
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
